name: Issue Title Contains Trigger and Node.js Script Execution

on:
  issues:
    types: [opened, edited]
  workflow_dispatch: # Permite ejecutar el flujo de trabajo manualmente
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta cada 6 horas

jobs:
  check-issue-and-run-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ACCES_TOKEN: ${{ secrets.ACCES_TOKEN }}
      GACTIONS_ACCESTOKEN: ${{ secrets.GACTIONS_ACCESTOKEN }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Check Issue Title and Extract Text
      id: extract_text
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        KEYWORD="ex" # Reemplaza con el texto que debe contener el título
        echo $ISSUE_TITLE
        if [[ "$ISSUE_TITLE" == *"$KEYWORD"* ]]; then
          echo "El título del issue contiene el texto clave. Extrayendo el texto adicional..."
          # Extrae el texto después del texto clave
          ADDITIONAL_TEXT=$(echo "$ISSUE_TITLE" | sed "s/.*$KEYWORD//")
          echo "Texto clave $ADDITIONAL_TEXT"
          echo "ADDITIONAL_TEXT=$ADDITIONAL_TEXT" >> $GITHUB_ENV
        else
          echo "El título del issue no contiene el texto clave."
          ADDITIONAL_TEXT=""
          echo "ADDITIONAL_TEXT=$ADDITIONAL_TEXT" >> $GITHUB_ENV
        fi

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Read Last Color from State File
      id: read_color
      run: echo "::set-output name=color::$(cat ./ultimo_color.txt)"

    - name: Run Node.js script with additional text
      run: node createPostV2.js topicsandsubtopics.json 1 "$ADDITIONAL_TEXT" "${{steps.read_color.outputs.color}}" && node instagramUpload.js
