name: Issue Title Contains Trigger and Node.js Script Execution

on:
  issues:
    types: [opened, edited]

jobs:
  check-issue-and-run-script:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      ACCES_TOKEN: ${{ secrets.ACCES_TOKEN }}
      GACTIONS_ACCESTOKEN: ${{ secrets.GACTIONS_ACCESTOKEN }}
      SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    if: github.event_name == 'issues' && github.event.action == 'opened'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts

    - name: Check Issue Title and Extract Text
      id: extract_text
      run: |
        ISSUE_TITLE="${{ github.event.issue.title }}"
        KEYWORD="ex" # Reemplaza con el texto que debe contener el título
        echo $ISSUE_TITLE
        if [[ "$ISSUE_TITLE" == *"$KEYWORD"* ]]; then
          echo "El título del issue contiene el texto clave. Extrayendo el texto adicional..."
          # Extrae el texto después del texto clave
          ADDITIONAL_TEXT=$(echo "$ISSUE_TITLE" | sed "s/.*$KEYWORD//")
          echo "Texto clave $ADDITIONAL_TEXT"
          echo "ADDITIONAL_TEXT=$ADDITIONAL_TEXT" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo "TITLE_CONTAINS=true" >> $GITHUB_ENV
        else
          echo "El título del issue no contiene el texto clave. Terminando el workflow..."
          echo "TITLE_CONTAINS=false" >> $GITHUB_ENV
        fi

    - name: Set up Node.js
      if: env.TITLE_CONTAINS == 'true'
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      if: env.TITLE_CONTAINS == 'true'
      run: npm install

    - name: Run Node.js script with additional text
      if: env.TITLE_CONTAINS == 'true'
      run: node createPostV2.js topicsandsubtopics.json 1 $ADDITIONAL_TEXT && node instagramUpload.js
